Add customer label parameter and a new method without prefix.
afiskon/promtail-client pull request #6
Opened 2022-06-05 10:48 UTC by sddwt

update: allow to change label every time, you can pass an empty string in the first parameter when you don't want to change label and use `client.config.Labels`.
add: add a new method `Logf` to submit a logline without prefix such as `ERROR`, `INFO` etc.

2022-06-06 09:40 UTC, afiskon commented
I'm not actively maintaining this library at the moment so I would appreciate somebody else's eyes on this PR

2022-06-06 09:41 UTC, afiskon commented on promtail/protoclient.go
> +	})*/
Please don't leave any commented pieces of code.

2022-06-06 09:41 UTC, afiskon commented on promtail/jsonclient.go
> +					// batch = []*jsonLogEntryLabel{}
Please don't leave any commented pieces of code.

2022-06-06 09:42 UTC, afiskon commented on promtail/common.go
> +
Please remove this.

2022-06-06 09:42 UTC, afiskon commented on examples/client-example/main.go
> +		PrintLevel:         promtail.ERROR,
I guess you executed go-fmt or something? Please submit this as a separate PR.

2022-06-06 09:43 UTC, afiskon commented on examples/client-example/main.go
> +	}
Please remove formatting changes from the PR, or submit them as a separate PR.

2022-06-06 09:44 UTC, afiskon requested changes
See the comments.

2022-06-06 09:49 UTC, afiskon commented
> you can pass an empty string in the first parameter when you don't want to change label

I don't think this is a good API, nor do I approve the break of the backward compatibility. Please provide new methods that allows to override the label if necessary and keep the existing API as is.

2022-06-11 06:52 UTC, sddwt commented
> > you can pass an empty string in the first parameter when you don't want to change label
> 
> I don't think this is a good API, nor do I approve the break of the backward compatibility. Please provide new methods that allow to override the label if necessary and keep the existing API as is.

Agree with that, I am going to change that API and comments above. Thanks for your time.

2022-06-11 08:00 UTC, sddwt commented
Just re-committed, please review it, thanks, I'll pull another commit with `go-formatted` later.

2022-06-11 08:01 UTC, sddwt commented
I just tested the new method `LogfWithLabel`, it works as expected.

2024-01-20 16:59 UTC, olopost commented
Is it possible to merge ?

2024-01-22 11:25 UTC, afiskon commented
Unfortunately I'm not actively maintaining this library at the moment. Feel free forking it.

2024-01-22 11:25 UTC, closed without merging